### ISSUE TITLE
Ajouter un code LED pour chaque action

### ISSUE THREAD

**Issue by BAAAL00** [lbo462/starflit#18]
### L'objectif est de créer un code LED pour chaque action afin d'avoir du debug en temps réel (et en plus c'est jolie) .
Par exemple :
 - collision avoidance = rouge
 - collision detection = vert
 - random detection = bleue
 - go forward = clignote
 - ect....

**Comment by MarsiaSec** [comment]
led ring blinks green when object detected

**Comment by MarsiaSec** [comment]
TODO:
- init sequence during RPi setup
- RPi sends msg when init OK
